name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
    
    - name: Verify build assets
      run: |
        echo "Checking build output:"
        ls -la dist/
        echo "Checking if assets directory exists:"
        ls -la dist/assets/ || echo "No assets directory found"
        echo "Checking index.html content:"
        head -20 dist/index.html
    
    - name: Add SPA fallback (404.html)
      run: cp dist/index.html dist/404.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist